language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
   - image="sparkpos/docker-nginx-php"
   - sed -i 's/UTC/CST/' ~/official-images/test/tests/utc/expected-std-out.txt

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
