name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - tag: 7.1-alpine
           Dockerfile: "7.1/alpine/Dockerfile"
           image: "sparkpos/docker-nginx-php:7.1-alpine"
         - tag: 7.2-alpine
           Dockerfile: "7.2/alpine/Dockerfile"
           image: "sparkpos/docker-nginx-php:7.2-alpine"
         - tag: 7.3-alpine
           Dockerfile: "7.3/alpine/Dockerfile"
           image: "sparkpos/docker-nginx-php:7.3-alpine"
         - tag: 7.4-alpine
           Dockerfile: "7.4/alpine/Dockerfile"
           image: "sparkpos/docker-nginx-php:7.4-alpine"
         - tag: 8.0-alpine
           Dockerfile: "8.0/alpine/Dockerfile"
           image: "sparkpos/docker-nginx-php:8.0-alpine"
         - tag: 8.1-alpine
           Dockerfile: "8.1/alpine/Dockerfile"
           image: "sparkpos/docker-nginx-php:8.1-alpine"
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ${{ matrix.Dockerfile }}
        tags: ${{ matrix.image }}
